## Publications:

Roger, E., Kellie, D., Slatyer, C., Brenton, P., Torresan, O., Wallis, E., Zerger, A. "Open access research infrastructures are critical for improving the accessibility and utility of citizen science: a case study of Australia’s national biodiversity infrastructure, the Atlas of Living Australia (ALA)". *Citizen Science: Theory and Practice*. 2023; 8(1):56. <https://doi.org/10.5334/cstp.564>

Kellie, D., Kar, F., Balasubramaniam, S., Schneider, M., Schwenke, A., Torresan, O., Waite, C., Fenker, J., Westgate, M. (2025). "Cleaning Biodiversity Data in R." (Version 0.2.0). <https://doi.org/10.54102/ala.77009>

## Contributions:

Torresan, O. & Kellie, D. "Show seasonal species trends using a ridgeline plot", ALA Labs (Atlas of Living Australia), published 10/5/2025. <https://labs.ala.org.au/posts/2024-05-10_ridgeline-plots/>

Smith, A., Torresan, O., & Kellie, D. "An exploration of dingo observations in the ALA", ALA Labs (Atlas of Living Australia), published 5/5/2023. <https://labs.ala.org.au/posts/2023-05-16_dingoes/>

Rushbook, T., Torresan, O., & Kellie, D. "Make a highlighted time series plot", ALA Labs (Atlas of Living Australia), published 3/4/2023. <https://labs.ala.org.au/posts/2023-04-03_highlighted-time-series/>

Torresan, O., & Kellie, D. "Counting points in multipolygon shapefiles for choropleth mapping", ALA Labs (Atlas of Living Australia), published 6/2/2023. <https://labs.ala.org.au/posts/2023-01-12_counting-points-in-shapefiles/>
